//
//  GeneralWebViewController.h
//  DELeaders
//
//  Created by anshim on 3/24/13.
//
//

#import <UIKit/UIKit.h>

@interface GeneralWebViewController : UIViewController <UIWebViewDelegate>
@property (weak, nonatomic) IBOutlet UIWebView *myWebView;

// Non-autogenerated properties
@property (nonatomic) NSString *myURL;
@property (nonatomic) NSString *myTitle;
@end
