//
//  SocialViewController.h
//  DELeaders
//
//  Created by anshim on 3/24/13.
//
//

#import <UIKit/UIKit.h>

@interface SocialViewController : UIViewController <UIWebViewDelegate>
@property (weak, nonatomic) IBOutlet UIWebView *myWebView;
@property (weak, nonatomic) IBOutlet UIButton *facebookButton;
@property (weak, nonatomic) IBOutlet UIButton *twitterButton;
@property (weak, nonatomic) IBOutlet UIButton *linkedInButton;
@property (weak, nonatomic) IBOutlet UIImageView *topImage;
@property (weak, nonatomic) IBOutlet UIImageView *bottomImage;

// Non-autogenerated properties
@property (nonatomic) NSString *myURL;
@property (nonatomic) NSString *myTitle;
@end
